import {Link} from "react-router-dom";
import {useLocation, useParams} from "react-router";
export default function CourseNavigation() {
    const links = ["Home", "Modules", "Piazza", "Zoom", "Assignments", "Quizzes", "Grades", "People"];
    const { cid } = useParams();
    const { pathname } = useLocation();
    const currentLink = pathname.split("/")[4];

    return (
        <div id="wd-courses-navigation" className="wd list-group fs-5 rounded-0">
            {/* This line of code was auto generated by my GitHub Co-Pilot plugin, and I modified it myself to include the cid part*/}
            {links.map((link) => (
                <Link to={`/Kambaz/Courses/${cid}/${link}`} key={link} id={`wd-course-${link.toLowerCase()}-link`}
                     // ^ As was this line below
                className={`list-group-item ${currentLink === link ? "active" : "text-danger"} border border-0`}>
                    {link}
                </Link>
            ))}
        </div>
    );}

/*        <div id="wd-courses-navigation" className="wd list-group fs-5 rounded-0">
    <Link to="/Kambaz/Courses/1234/Home" id="wd-course-home-link"
          className="list-group-item active border border-0"> Home </Link><br />
    <Link to="/Kambaz/Courses/1234/Modules" id="wd-course-modules-link"
          className="list-group-item text-danger border border-0"> Modules </Link><br />
    <Link to="/Kambaz/Courses/1234/Piazza" id="wd-course-piazza-link"
          className="list-group-item text-danger border border-0"> Piazza </Link><br />
    <Link to="/Kambaz/Courses/1234/Zoom" id="wd-course-zoom-link"
          className="list-group-item text-danger border border-0"> Zoom </Link><br />
    <Link to="/Kambaz/Courses/1234/Assignments" id="wd-course-quizzes-link"
          className="list-group-item text-danger border border-0"> Assignments </Link><br />
    <Link to="/Kambaz/Courses/1234/Quizzes" id="wd-course-assignments-link"
          className="list-group-item text-danger border border-0"> Quizzes </Link><br />
    <Link to="/Kambaz/Courses/1234/People" id="wd-course-people-link"
          className="list-group-item text-danger border border-0" > People </Link><br />
</div>*/


